In [1]:
import numpy as np

In [ ]:
num_orbitals = 2
spin_degen = 2

np.random.seed(0)
C = np.random.uniform(-1, 1, (num_orbitals * spin_degen, num_orbitals * spin_degen))

In [41]:
rho = C.T @ C

In [42]:
rho

array([[ 0.91129826, -0.10287384,  0.46341812, -0.16966076],
       [-0.10287384,  1.04923973, -0.81424285, -0.44907429],
       [ 0.46341812, -0.81424285,  1.13427692,  0.66278687],
       [-0.16966076, -0.44907429,  0.66278687,  1.30719086]])

In [43]:
new_rho = rho.reshape(num_orbitals, spin_degen, num_orbitals, spin_degen).swapaxes(1, 2)

In [44]:
rho[:spin_degen, :spin_degen], new_rho[0, 0]

(array([[ 0.91129826, -0.10287384],
        [-0.10287384,  1.04923973]]),
 array([[ 0.91129826, -0.10287384],
        [-0.10287384,  1.04923973]]))

In [46]:
new_rho[0, 1]

array([[ 0.46341812, -0.16966076],
       [-0.81424285, -0.44907429]])

In [63]:
flipped = np.copy(new_rho)
flipped[..., 0, 0], flipped[..., 1, 1] = new_rho[..., 1, 1], new_rho[..., 0, 0]
flipped[..., 0, 1], flipped[..., 1, 0] = new_rho[..., 1, 0], new_rho[..., 0, 1]

In [65]:
new_rho, flipped

(array([[[[ 0.91129826, -0.10287384],
          [-0.10287384,  1.04923973]],
 
         [[ 0.46341812, -0.16966076],
          [-0.81424285, -0.44907429]]],
 
 
        [[[ 0.46341812, -0.81424285],
          [-0.16966076, -0.44907429]],
 
         [[ 1.13427692,  0.66278687],
          [ 0.66278687,  1.30719086]]]]),
 array([[[[ 1.04923973, -0.10287384],
          [-0.10287384,  0.91129826]],
 
         [[-0.44907429, -0.81424285],
          [-0.16966076,  0.46341812]]],
 
 
        [[[-0.44907429, -0.16966076],
          [-0.81424285,  0.46341812]],
 
         [[ 1.30719086,  0.66278687],
          [ 0.66278687,  1.13427692]]]]))

In [64]:
flipped

array([[[[ 1.04923973, -0.10287384],
         [-0.10287384,  0.91129826]],

        [[-0.44907429, -0.81424285],
         [-0.16966076,  0.46341812]]],


       [[[-0.44907429, -0.16966076],
         [-0.81424285,  0.46341812]],

        [[ 1.30719086,  0.66278687],
         [ 0.66278687,  1.13427692]]]])

In [47]:
new_new_rho = new_rho.swapaxes(-1, -2)
new_new_rho[0, 1]

array([[ 0.46341812, -0.81424285],
       [-0.16966076, -0.44907429]])

In [58]:
Q_rho = np.flip(new_rho)
Q_rho[0, 1]

array([[-0.44907429, -0.16966076],
       [-0.81424285,  0.46341812]])

In [60]:
new_rho

array([[[[ 0.91129826, -0.10287384],
         [-0.10287384,  1.04923973]],

        [[ 0.46341812, -0.16966076],
         [-0.81424285, -0.44907429]]],


       [[[ 0.46341812, -0.81424285],
         [-0.16966076, -0.44907429]],

        [[ 1.13427692,  0.66278687],
         [ 0.66278687,  1.30719086]]]])

In [59]:
Q_rho

array([[[[ 1.30719086,  0.66278687],
         [ 0.66278687,  1.13427692]],

        [[-0.44907429, -0.16966076],
         [-0.81424285,  0.46341812]]],


       [[[-0.44907429, -0.81424285],
         [-0.16966076,  0.46341812]],

        [[ 1.04923973, -0.10287384],
         [-0.10287384,  0.91129826]]]])

In [51]:
rho

array([[ 0.91129826, -0.10287384,  0.46341812, -0.16966076],
       [-0.10287384,  1.04923973, -0.81424285, -0.44907429],
       [ 0.46341812, -0.81424285,  1.13427692,  0.66278687],
       [-0.16966076, -0.44907429,  0.66278687,  1.30719086]])

In [ ]:
new_new_rho.swapaxes(1, 2).reshape(num_orbitals * spin_degen, num_orbitals * spin_degen)

array([[ 0.91129826, -0.10287384,  0.46341812, -0.81424285],
       [-0.10287384,  1.04923973, -0.16966076, -0.44907429],
       [ 0.46341812, -0.16966076,  1.13427692,  0.66278687],
       [-0.81424285, -0.44907429,  0.66278687,  1.30719086]])